keep hard failure

diff --git a/salt/elasticfleet/tools/sbin_jinja/so-elastic-fleet-integration-upgrade b/salt/elasticfleet/tools/sbin_jinja/so-elastic-fleet-integration-upgrade
--- a/salt/elasticfleet/tools/sbin_jinja/so-elastic-fleet-integration-upgrade
+++ b/salt/elasticfleet/tools/sbin_jinja/so-elastic-fleet-integration-upgrade
@@ -57,11 +57,11 @@ for AGENT_POLICY in $agent_policies; do
                         elastic_fleet_integration_policy_upgrade "$INTEGRATION_ID"
                         if [ $? -ne 0 ]; then
                             echo "Error: Upgrade failed for $PACKAGE_NAME with integration ID '$INTEGRATION_ID'."
-                            continue
+                            exit 1
                         fi
                     else
-                        echo "Errors detected during dry run. Skipping $PACKAGE_NAME policy upgrade..."
-                        continue
+                        echo "Errors detected during dry run for $PACKAGE_NAME policy upgrade..."
+                        exit 1
                     fi
                 fi
             {%- if not AUTO_UPGRADE_INTEGRATIONS %}
